#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge $HOME/.Xresources
eval $(gpg-agent --daemon)
$HOME/bin/apod-helper &
urxvtd -f
pulseaudio -D
nohup redshift >/dev/null 2>/dev/null &
compton --backend glx &
xsetroot -cursor_name left_ptr
setxkbmap us -option compose:rctrl -option terminate:ctrl_alt_bksp
xset r rate 200 60
exec $HOME/.cabal/bin/xmonad
