#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge $HOME/.Xresources
pgrep gpg-agent || eval $(gpg-agent --daemon)
pulseaudio -D
systemctl --user start compton
systemctl --user start urxvtd
systemctl --user start dunst
systemctl --user start udiskie
systemctl --user start redshift
xsetroot -cursor_name left_ptr
setxkbmap us -option compose:rctrl -option terminate:ctrl_alt_bksp
xset r rate 200 60
xset +dpms
feh --bg-center ~/pics/earth_moon.jpg
exec $HOME/.cabal/bin/xmonad
