#Set our umask
umask 022

# Set our default path
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:$HOME/bin"
export PATH

# Termcap is outdated, old, and crusty, kill it.
unset TERMCAP

# Man is much better than us at figuring this out
unset MANPATH

export SSLKEYLOGFILE=$HOME/.sslkeylog

# start X on login
if [[ -z $DISPLAY ]] && [[ $TTY = /dev/tty1 ]] ; then
  rm -f $SSLKEYLOGFILE
  echo sudo Fn keys
  echo 0 | sudo tee /sys/module/hid_apple/parameters/fnmode
  exec startx
fi

# temp fix
#xrdb -merge ~/.Xresources

#history
HISTFILE=~/.histfile
HISTSIZE=2000
SAVEHIST=2000
setopt hist_ignore_dups
setopt sharehistory

#fix keys
# bindkey '^?' backward-delete-char
# bindkey '^[[7~' beginning-of-line
# bindkey '^[[5~' up-line-or-history
# bindkey '^[[3~' delete-char
# bindkey '^[[8~' end-of-line
# bindkey '^[[6~' down-line-or-history
# bindkey '^[[A' up-line-or-search
# bindkey '^[[D' backward-char
# bindkey '^[[B' down-line-or-search
# bindkey '^[[C' forward-char
# bindkey '^[[2~' overwrite-mode

# rework on fixing my keys!
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
if [[ $TERM = xterm ]] || [[ $TERM = xterm-256color ]]; then
  bindkey '^[[H' beginning-of-line
  bindkey '^[[F' end-of-line
elif [[ $TERM = rxvt ]]; then
  bindkey '^[[7~' beginning-of-line
  bindkey '^[[8~' end-of-line
fi
bindkey '^[[3~' delete-char

#autocomplete
fpath=(~/.zsh/completion $fpath)
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit
#sudo completion
zstyle ':completion:*:sudo:*' $PATH
#menu completion
zstyle ':completion:*' menu select
# case-insensitive,partial-word and then substring completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
setopt completealiases

#better globbing
setopt extendedglob

#prompt
autoload -U colors
colors

PROMPT='%B%m%b> '
RPROMPT='%~ %(?..[%?] )%*'

# colors
[[ -z $LS_COLORS ]] && eval $(dircolors -b ~/.zsh/LS_COLORS/LS_COLORS)

#aliases
local LS_ALIAS='ls -l --classify --human-readable --color=always --group-directories-first --quoting-style=literal --time-style long-iso'
alias ls="$LS_ALIAS"
alias sl="sl && $LS_ALIAS"
alias cp='cp --verbose'
alias mv='mv --verbose --interactive'
alias rm='rm --verbose'
alias grep='LANG=C grep --color=auto'
alias egrep='LANG=C egrep --color=auto'
alias tree='tree -L 2 --dirsfirst'
alias sd='sudo systemctl'
alias pgrep='pgrep --list-full'
alias ag='LANG=C ag --ignore-dir node_modules'
alias pstree='pstree --arguments --highlight-all --long --ascii --uid-changes'
alias tm='tmux attach || tmux new'

export EDITOR=/usr/bin/vim
export BROWSER=/usr/bin/firefox

# welcome line
if [[ ! -z $COLUMNS ]]; then
    DATESTR=$(date +'%A, %_d %B %Y')
    USERHOST='\e[1;37m'$USER'\e[0m at \e[1;37m'$HOST'\e[0m'
    printf "$USERHOST%$(expr $COLUMNS - ${#DATESTR} - ${#USERHOST} + 25)s$DATESTR\n"
    unset DATESTR
    unset USERHOST
else
    echo "$USER@$HOST - $(date +'%A, %d %B %Y - %H:%M.%S')"
fi

source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[globbing]='fg=white,bold'

function serve() {
    PORT=$(expr 65536 - $$)
    (sleep 2 && $BROWSER http://127.0.0.1:$PORT/ )&
    python -m http.server $PORT
}

source $HOME/.zsh/ap/ap.zsh

function m() {
  if [[ "$1" != "" ]]; then
    echo udevil mount /dev/$1
    udevil mount /dev/$1
  fi
  echo mounted media:
  grep media =(df -h)
}

function u() {
  echo udevil umount /dev/$1
  udevil umount /dev/$1
  if [[ $1 = sr0 ]]; then
    echo eject /dev/sr0
    eject /dev/sr0
  fi
  echo mounted media:
  grep media =(df -h)
}

function bak() {
  cp -r $1 $1.$(date +%Y%m%d-%H%M%S)
}

PATH="/home/milky/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/milky/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/milky/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/milky/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/milky/perl5"; export PERL_MM_OPT;

# export TERM=xterm-256color
# source $HOME/.zsh/powerlevel9k/powerlevel9k.zsh-theme
# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)


# fortune -sa it
